#!/usr/bin/env python3
"""
Generate a small JS bundle (viewer/data.js) that exposes the zine
database as a global `window.ZINES` array for the static viewer.

Why: Browsers often block `fetch()` for local file:// URLs. Emitting a
plain JS file avoids CORS issues and keeps the viewer fully offline.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "punk_zines_database.json"
OUT_DIR = ROOT / "docs"
OUT_PATH = OUT_DIR / "data.js"


def normalize_year(s: str | int | None) -> int | None:
    """Return a best-effort primary year as int (e.g., "1977-1980" -> 1977)."""
    if s is None:
        return None
    if isinstance(s, int):
        return s
    # find first 4-digit number
    for i in range(len(s) - 3):
        fragment = s[i : i + 4]
        if fragment.isdigit():
            try:
                year = int(fragment)
                if 1900 <= year <= 2100:
                    return year
            except ValueError:
                pass
    return None


def derive_ia_thumb(ia_item_url: str | None) -> str | None:
    """Given an Internet Archive item URL, return the thumbnail URL.

    Example: https://archive.org/details/maximumrnr ->
             https://archive.org/services/img/maximumrnr
    """
    if not ia_item_url:
        return None
    marker = "/details/"
    if marker not in ia_item_url:
        return None
    item_id = ia_item_url.split(marker, 1)[1].split("/", 1)[0].split("?", 1)[0]
    if not item_id:
        return None
    return f"https://archive.org/services/img/{item_id}"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    data = json.loads(DB_PATH.read_text())

    zines = data.get("zines", [])
    minimized = []
    for z in zines:
        # Keep a focused subset needed by the viewer; include all user-facing fields.
        img_url = z.get("image_url")
        local_image = None
        if img_url and not str(img_url).lower().startswith(("http://", "https://", "data:")):
            # Compute a path relative to the viewer directory so images load when
            # opening viewer/index.html directly from the filesystem.
            # Many entries store paths like "images/<file>.jpg" relative to project root.
            src = (ROOT / str(img_url).lstrip("./")).resolve()
            try:
                rel = os.path.relpath(src, OUT_DIR)
            except Exception:
                rel = str(img_url)
            local_image = rel
        entry = {
            "id": z.get("id"),
            "zine_name": z.get("zine_name"),
            "issue_number": z.get("issue_number"),
            "year": z.get("year"),
            "year_primary": normalize_year(z.get("year")),
            "location": z.get("location"),
            "description": z.get("description"),
            "tags": z.get("tags", []),
            "bands_featured": z.get("bands_featured", []),
            "creators": z.get("creators"),
            "source_type": z.get("source_type"),
            "archive_source": z.get("archive_source"),
            "image_url": img_url,
            "local_image": local_image,
            "ia_item_url": z.get("ia_item_url"),
            "ia_download_url": z.get("ia_download_url"),
            "ia_thumb": derive_ia_thumb(z.get("ia_item_url")),
        }
        minimized.append(entry)

    # Emit compact JS to keep file size down.
    payload = json.dumps(minimized, ensure_ascii=False, separators=(",", ":"))
    js = (
        "// Auto-generated by tools/generate_data_js.py — do not edit by hand\n"
        "window.ZINES = "
        + payload
        + ";\n"
    )
    OUT_PATH.write_text(js)
    print(f"Wrote {OUT_PATH} with {len(minimized)} records")


if __name__ == "__main__":
    main()
